### ISSUE TITLE
DEdit for Jupiter - crashes when easily overloaded.

### ISSUE THREAD

**Issue by WildChargerTV** [narzoul/DDrawCompat#276]
I'd like to preface this submission by saying this is definitely an outlandish scenario, and may not actually indicate a problem with DDrawCompat itself. I'm submitting this because I want to ensure all of my bases are covered.

The program I'm using is not a game in and of itself; rather, it is a world editor program for the LithTech Jupiter engine named "DEdit". I have checked the list of unsupported cases and confirmed that this program does not fall under any of those categories. (The game for which the program was made does not suffer from these problems.) For reasons I've not yet been able to figure out, this program appears to have become wildly unstable running on any modern Intel hardware (post 2020), constantly crashing with unspecified access violation errors. DDrawCompat was the only thing I've been able to use thus far to stabilize the program (for the most part) with a significant performance reduction; however, attempting to close larger world files will still cause crashes for the same access violations.

Limited testing was done on two other sets of hardware. Neither had problems remotely like this.

[The log file for this run is here.](https://github.com/narzoul/DDrawCompat/files/13806208/DDrawCompat-dedit.log) Although I did use a lot of process-specific configuration settings, because the crash in question is easily replicatable, I can say with relative confidence that very few, if any, of these settings have had any performance impact or have been able to make the crash avoidable following testing.

[The mini-crash dump is here.](https://github.com/narzoul/DDrawCompat/files/13806205/DDrawCompat-dedit.dmp) A full one can be provided if needed. 

I am already (painfully) aware that the 0xc0000005 error could apply to literally anything under the sun, but if nothing else, it would at least give me peace of mind if I knew the culprit was elsewhere beyond this wrapper. Any potential insight would be appreciated.

**Comment by narzoul** [comment]
The crash you posted should be fixed by v0.5.2, though I'm not sure because I wasn't able to reproduce it with earlier versions either.
I don't know about the performance issues, I'd need more info on how to reproduce them exactly. Since your GPU was using D3D9On12 by default, v0.5.2 should now automatically switch it to igd9trinity32.dll instead, which hopefully will have better performance as well.

**Comment by WildChargerTV** [comment]
You're a miracle worker, friend. The crashes have indeed mostly dissipated, as have the performance issues. I'm not sure if you were able to actually go out of your way to install this software yourself, but if that's what you did, I can't thank you enough. This was the only major barrier to making the software work with my laptop, and although it's still not perfect (viewports don't tend to show anything until I've switched to software rendering and then back to hardware manually), it's far better than it was before.

If there's anything else posing an issue I'll let you know. Thanks again!

**Comment by narzoul** [comment]
> viewports don't tend to show anything until I've switched to software rendering and then back to hardware manually

This may have been caused by the windowed mode presentation issue in v0.5.2. Is it by chance fixed in v0.5.3? If not, I'll need some more help on how to reproduce the problem, as I haven't even figured out how to load anything in the editor yet.

**Comment by WildChargerTV** [comment]
No, unfortunately the issue is not fixed in v0.5.3. Reproducing the problem should be as simple as attempting to create a new World file, but I've not seen DEdit without preset functionality before, so we may just not be using the same program, so to speak.

The version of DEdit I'm using is bundled alongside the editing tools for the game TRON 2.0. For me, the build number is 109.21. I'll assemble a video showing current vs. intended behavior when I get the chance - however unfortunately I cannot send you a working world file to open for yourself, as this version is (to my knowledge) quite closely tied to the unique version of LithTech that runs the game (LithTech Triton). Getting that specific version may be the only way we can actually compare results.

Its editing tools are a separate install from the game itself, but upon doing so you'd be provided with a preset project file that loads everything needed for you to run your tests. (The installer bundle also comes with its own uninstaller that can clean up all of the other software once you're done.)

**Comment by WildChargerTV** [comment]
I didn't have much time to put this video together, so I apologize for the imperfections. A caption denotes what segment of the video is currently playing.

https://youtu.be/JT_uyzKaoWI

**Comment by narzoul** [comment]
I had another look at this. It's using multiple primary surfaces simultaneously, which was never supported by DDrawCompat under the assumption that DirectDraw applications would generally only use one primary surface (you never really need more than one). Adding support for this would require some major refactoring and a lot of effort, and since this is the only known app that needs it so far, it's unlikely to be done anytime soon, if ever. It's also far more likely to break a lot more things than it would fix, so it would need to be done with extreme care and a ton of testing.

I'll leave this open in case I get very bored and have nothing better to do for a couple of days/weeks, but don't get your hopes up for a fix in the near future.

**Comment by WildChargerTV** [comment]
That's perfectly okay, the fixes you've done so far have been more than helpful. I'll take this over a crashing mess. Feel free to follow-up if/when you ever get the time. Thank you for your help regardless.

**Comment by elishacloud** [comment]
> It's using multiple primary surfaces simultaneously, which was never supported by DDrawCompat under the assumption that DirectDraw applications would generally only use one primary surface (you never really need more than one).

@narzoul, I have a few questions about this issue:

1. Are you sure that multiple primary surfaces are created in the same DirectDraw device?  Because multiple devices can be created and there could be a different primary surface for each device and each device could have a different window it is presenting to.
2. What's the purpose of the DDERR_PRIMARYSURFACEALREADYEXISTS error if it’s ok to create more than one primary surface?  I thought native ddraw doesn't allow multiple primary surfaces in the same device?
3. If there are multiple primary surfaces, how does DirectDraw know which primary surface to use when presenting?

**Comment by elishacloud** [comment]
Thanks @narzoul!  That makes sense.  I just wanted to make sure I understand DirectDraw.  The documentation in some places in not very clear, IMHO.
